messages = {
    # main
    "fonct_consol": "\n1. Play    2. Options    3. Quit",
    "q_fonct_consol": "\nEnter a number corresponding to the desired function : ",
    "mode_fonct_consol": "\n1. VS    2. Back    3. Quit",
    "error_valide_number": "\nEnter a valid number !!",
    "error_not_number": "\nEnter a number !!",
    "param_consol": "\n1. Language    2. Auto name    3. Back    4. Quit",
    "q_param_consol": "\nEnter a number corresponding to the desired option : ",
    "lang_option": "\n1. FR    2. EN    3. Back    4. Quit",
    "q_lang_option": "\nEnter a number corresponding to the desired language : ",
    "vs_a": "Enter the number of player against the b team : ",
    "vs_b": "Enter the number of player against the a team : ",
    "auto_name": "1. Yes    2. No    3. Back    4. Quit",
    "q_auto_name": "Enter a number corresponding to the desired value : ",

    # VS
    "enter_name_player": "Enter the name of player",
    "no_weapon": "No weapon",
    "warning_no_weapon": "\nWarning !! Both players have no weapon, the combat may last a long time !!",
    "pass_enter": "\nWrite 'pass' to skip the combat and only see the results or press 'Enter' : ",
    "error_pass_enter": "\nError !! Write 'pass' or press 'Enter'!",
    "number_rounds": "\nNumber of rounds : ",
    "number_events": "Number of events : ",
    "event_list": "\nEvent list",
    "no_event": "No events",
    "tableau_player": "Player",
    "tableau_total_damage": "Total damage received",
    "press_enter": "\nPress 'Enter' to continue : ",
    "initial_stat_player": "\nInitial stats of the players : ",
    "round": "Round ",
    "tableau_damage_HP": "Damage received    Remaining HP",
    "both": "Both",
    "message_view_stat": "\nEnter the player number to view their stats (press 'Enter' to skip) : ",
    "has_died": "has died !",
    "pass": "pass",
    "tableau_team": "Team",
    "auto_name_for": "player ",

    # weapon_mode
    "name_single_shot": "Single shot",
    "name_automatic": "Automatic",
    "name_burst_fire": 'Burst fire',
    "name_9mm": "9mm",
    "name_barrett_m81": "Barrett M81",
    "name_spas12": "Spas12",
    "name_phamas": "Phamas",
    "name_god_rifle": "God rifle",
    "name_lightning": "Lightning",
    "uses": "uses",
    "hp_restored": "hp restored",
    "stat_for": "Stats for",
    "hp": "HP",
    "weapon": "Weapon",
    "ammo_type": "Ammo type",
    "no_ammo": "No ammo",
    "mode": "Mode",
    "no_mode": "No mode",
    "armor": "Armor",
    "damage_on": "damage inflicted on",

    # healing
    "name_small_potion": "Small potion",
    "name_medium_potion": "Medium potion",

    # event
    "inflicts": "inflicts",
    "damage_to": "damage to",
    "name_event_storm": "Storm",
    "name_event_program_error": "Program Error",
    "name_no_armor": "No armor",
    "name_wood_armor": "Wood armor",
    "name_iron_armor": "Iron armor",
    "name_god_armor": "God armor",
    "name_normal_ammo": "Normal ammo",
    "name_explosive_ammo": "Explosive ammo"
}
