messages = {
    # main
    "fonct_consol": "\n1. Jouer    2. Options    3. Quitter",
    "q_fonct_consol": "\nSaisissez un numéro correspondant à la fonction souhaitée : ",
    "mode_fonct_consol": "\n1. VS    2. Retour    3. Quitter",
    "error_valide_number": "\nEntrez un numéro valide !!",
    "error_not_number": "\nEntrez un numéro !!",
    "param_consol": "\n1. Langage    2. Retour    3. Quitter",
    "q_param_consol": "\nSaisissez un numéro correspondant à l'option souhaitée : ",
    "lang_option": "\n1. FR    2. EN    3. Retour    4. Quitter",
    "q_lang_option": "\nSaisissez un numéro correspondant au langage souhaitée : ",
    "vs_a": "Entrez le nombre de joueurs contre l'équipe b : ",
    "vs_b": "Entrez le nombre de joueurs contre l'équipe a : ",

    # VS
    "enter_name_player": "Entrez le nom du joueur",
    "no_weapon": "Aucune arme",
    "warning_no_weapon": "\nAttention !! Les deux joueurs n'ont pas d'arme, le combat risque de durer longtemps !!",
    "pass_enter": "\nÉcrivez 'passer' pour ignorer le combat et voir uniquement les résultats ou appuyez sur 'Entrée' : ",
    "error_pass_enter": "\nErreur !! Écrivez 'passer' ou appuyez sur 'Entrée' !",
    "number_rounds": "\nNombre de rounds : ",
    "number_events": "Nombre d'évents : ",
    "event_list": "\nListe des évents",
    "no_event": "Pas d'évent",
    "tableau_player": "Joueur",
    "tableau_total_damage": "Total des dégâts reçus",
    "press_enter": "\nAppuyer sur 'Entrée' pour continuer : ",
    "initial_stat_player": "\nStats initiales des joueurs : ",
    "round": "Round ",
    "tableau_damage_HP": "Dommages reçus    PV restants",
    "both": "Les deux",
    "message_view_stat": "\nEntrez le numéro du joueur pour afficher ses stats (appuyez sur 'Entrée' pour ignorer) : ",
    "has_died": "est mort !",
    "pass": "passer",

    # weapon_mode
    "name_single_shot": "Tire unique",
    "name_automatic": "Automatique",
    "name_burst_fire": "Tir en rafale",
    "name_9mm": "9mm",
    "name_barrett_m81": "Barrett M81",
    "name_spas12": "Spas12",
    "name_phamas": "Phamas",
    "name_god_rifle": "Fusil de dieu",
    "name_lightning": "Foudre",
    "uses": "utilises",
    "hp_restored": "PV réstoré",
    "stat_for": "Stats de",
    "hp": "PV",
    "weapon": "Arme",
    "ammo_type": "Type de munition",
    "no_ammo": "Aucune munition",
    "mode": "Mode",
    "no_mode": "Aucun mode",
    "armor": "Armure",
    "damage_on": "dommages infligés à",

    # healing
    "name_small_potion": "Petite potion",
    "name_medium_potion": "Potion moyenne",

    # event
    "inflicts": "inflige",
    "damage_to": "dégats à",
    "name_event_storm": "Tempête",
    "name_event_program_error": "Erreur programme",
    "name_no_armor": "Aucune armure",
    "name_wood_armor": "Armure en bois",
    "name_iron_armor": "Armure en fer",
    "name_god_armor": "Armure de dieu",
    "name_normal_ammo": "Munition normal",
    "name_explosive_ammo": "Munition explosive"
}
